# Site wide configuration

title: Skinny Bones
description: "A lightweight site starter for Jekyll"
logo: 120x120.gif
teaser: 400x250.gif
locale: en_US
url:

# Jekyll configuration

source: _source
sass:
    sass_dir: _sass
    style: compressed
permalink: /:categories/:title/
markdown: kramdown
highlighter: pygments
gems:
  - jekyll-sitemap


# Site owner
owner:
  name: Michael Rose
  email: michael@mademistakes.com
  twitter: mmistakes
  bio: "Just another boring, tattooed, time traveling designer."
  avatar: bio-photo.jpg
disqus-shortname:


exclude: ["lib", "config.rb", ".sass-cache", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "*.sublime-project", "*.sublime-workspace", "Gemfile", "Gemfile.lock", "README.md", "LICENSE", "node_modules", "Gruntfile.js", "package.json"]
